services:
  backend:
    build: ./src/chatbot-backend
    image: fastapi-backend
    container_name: fastapi-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src/chatbot-backend:/app

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: vue-frontend
    container_name: vue-frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      VITE_API_URL: "http://backend:8000"
      HOST: "0.0.0.0"
      PORT: "8080"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: npm run dev